"use client";

import { apiFetch } from "@/lib/api";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {ArrowDownToLine,ArrowUpFromLine,Clock3,RefreshCcw,Search,UserRoundCheck} from "lucide-react";
import {Button} from "@/components/ui/Button";
import {Toast} from "@/components/ui/Toast";
import {entetesAuthentifiees} from "@/lib/auth";
import { MaterielTabs } from "@/components/materiel/MaterielTabs";
import styles from "./page.module.css";

const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000";
const datefr=(v:any)=>v?new Intl.DateTimeFormat("fr-FR").format(new Date(v)):"—";

export default function Page(){
 const[data,setData]=useState<any[]>([]),[refs,setRefs]=useState<any>({materiels:[],utilisateurs:[],affaires:[],emplacements:[]}),[q,setQ]=useState(""),[modal,setModal]=useState(false),[ret,setRet]=useState<any>(null),[toast,setToast]=useState<any>(null);
 const[f,setF]=useState<any>({materiel_id:"",emprunteur_id:"",affaire_id:"",site_zone:"",date_retour_prevue:"",commentaire_sortie:""});
 async function load(){try{const h=entetesAuthentifiees();const[a,b]=await Promise.all([apiFetch(`${API}/api/prets-materiel`,{headers:h}),apiFetch(`${API}/api/prets-materiel/referentiels`,{headers:h})]);if(!a.ok||!b.ok)throw 0;setData(await a.json());setRefs(await b.json())}catch{setToast({type:"error",message:"Impossible de charger les prêts de matériel."})}}
 useEffect(()=>{load()},[]);
 const visibles=useMemo(()=>{const t=q.toLowerCase().trim();return data.filter(x=>!t||[x.reference,x.numero_inventaire,x.designation,x.emprunteur,x.affaire_reference,x.affaire_nom,x.site_zone].some(v=>String(v??"").toLowerCase().includes(t)))},[data,q]);
 async function creer(e:FormEvent){e.preventDefault();const r=await apiFetch(`${API}/api/prets-materiel`,{method:"POST",headers:entetesAuthentifiees({"Content-Type":"application/json"}),body:JSON.stringify({materiel_id:Number(f.materiel_id),emprunteur_id:f.emprunteur_id?Number(f.emprunteur_id):null,affaire_id:f.affaire_id?Number(f.affaire_id):null,site_zone:f.site_zone||null,date_retour_prevue:f.date_retour_prevue,commentaire_sortie:f.commentaire_sortie||null})});const d=await r.json().catch(()=>null);if(!r.ok){setToast({type:"error",message:d?.detail??"Prêt impossible."});return}setModal(false);setToast({type:"success",message:`${d.reference} créé.`});load()}
 async function retour(e:FormEvent){e.preventDefault();const r=await apiFetch(`${API}/api/prets-materiel/${ret.id}/retour`,{method:"POST",headers:entetesAuthentifiees({"Content-Type":"application/json"}),body:JSON.stringify({emplacement_retour_id:Number(ret.emplacement_retour_id),etat_retour:ret.etat_retour,commentaire_retour:ret.commentaire_retour||null})});const d=await r.json().catch(()=>null);if(!r.ok){setToast({type:"error",message:d?.detail??"Retour impossible."});return}setRet(null);setToast({type:"success",message:"Retour matériel enregistré."});load()}
 const actifs=data.filter(x=>x.statut!=="RETOURNE"),retards=data.filter(x=>x.statut==="EN_RETARD");
 return <div><div className="breadcrumb">Stocks / Prêts matériel</div><MaterielTabs /><div className="page-heading page-heading-actions"><div><span className="eyebrow">Matériel COREF</span><h1>Prêts de matériel</h1><p>Sorties temporaires, affectations et retours du matériel individualisé.</p></div><div className={styles.actions}><Button variant="secondary" onClick={load}><RefreshCcw size={17}/>Actualiser</Button><Button onClick={()=>{setF({materiel_id:"",emprunteur_id:"",affaire_id:"",site_zone:"",date_retour_prevue:"",commentaire_sortie:""});setModal(true)}}><ArrowUpFromLine size={17}/>Nouveau prêt</Button></div></div>
 <section className={styles.kpis}><article><UserRoundCheck/><span>Prêts actifs</span><strong>{actifs.length}</strong></article><article className={styles.warning}><Clock3/><span>En retard</span><strong>{retards.length}</strong></article><article><ArrowDownToLine/><span>Retours enregistrés</span><strong>{data.filter(x=>x.statut==="RETOURNE").length}</strong></article><article><span>Matériels disponibles</span><strong>{refs.materiels.filter((x:any)=>x.disponible_pour_pret).length}</strong></article></section>
 <section className={styles.panel}><div className={styles.toolbar}><label className="search-field"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Prêt, matériel, personne, affaire ou site…"/></label></div><table className={styles.table}><thead><tr><th>Prêt</th><th>Matériel</th><th>Détenteur / affaire</th><th>Sortie</th><th>Retour prévu</th><th>Statut</th><th>État</th><th></th></tr></thead><tbody>{visibles.map(x=><tr key={x.id}><td><strong>{x.reference}</strong></td><td><strong>{x.numero_inventaire}</strong><br/><span>{x.designation}</span></td><td>{x.emprunteur&&<><strong>{x.emprunteur}</strong><br/></>}{x.affaire_reference&&<span>{x.affaire_reference} — {x.affaire_nom}</span>}{x.site_zone&&<><br/><span>{x.site_zone}</span></>}</td><td>{datefr(x.date_sortie)}</td><td>{datefr(x.date_retour_prevue)}</td><td><span className={`${styles.badge} ${x.statut==="EN_RETARD"?styles.late:""}`}>{x.statut.replaceAll("_"," ")}</span></td><td>{x.etat_retour??x.etat_depart}</td><td>{x.statut!=="RETOURNE"?<button onClick={()=>setRet({...x,emplacement_retour_id:x.emplacement_depart_id?String(x.emplacement_depart_id):"",etat_retour:"DISPONIBLE",commentaire_retour:""})}>Enregistrer retour</button>:"—"}</td></tr>)}{!visibles.length&&<tr><td colSpan={8} className={styles.empty}>Aucun prêt.</td></tr>}</tbody></table></section>
 {modal&&<div className={styles.overlay}><form className={styles.modal} onSubmit={creer}><h2>Nouveau prêt</h2><label>Matériel *<select required value={f.materiel_id} onChange={e=>setF({...f,materiel_id:e.target.value})}><option value="">Sélectionner…</option>{refs.materiels.filter((x:any)=>x.disponible_pour_pret).map((x:any)=><option key={x.id} value={x.id}>{x.numero_inventaire} — {x.designation} — {x.categorie}</option>)}</select></label><label>Emprunteur COREF<select value={f.emprunteur_id} onChange={e=>setF({...f,emprunteur_id:e.target.value})}><option value="">Aucun</option>{refs.utilisateurs.map((x:any)=><option key={x.id} value={x.id}>{x.nom_complet}{x.fonction?` — ${x.fonction}`:""}</option>)}</select></label><label>Affaire<select value={f.affaire_id} onChange={e=>setF({...f,affaire_id:e.target.value})}><option value="">Aucune</option>{refs.affaires.map((x:any)=><option key={x.id} value={x.id}>{x.reference} — {x.nom}</option>)}</select></label><label>Site / zone<input value={f.site_zone} onChange={e=>setF({...f,site_zone:e.target.value})}/></label><label>Retour prévu *<input type="date" required value={f.date_retour_prevue} onChange={e=>setF({...f,date_retour_prevue:e.target.value})}/></label><label>Commentaire<textarea value={f.commentaire_sortie} onChange={e=>setF({...f,commentaire_sortie:e.target.value})}/></label><div className={styles.modalActions}><Button type="button" variant="secondary" onClick={()=>setModal(false)}>Annuler</Button><Button type="submit">Valider le prêt</Button></div></form></div>}
 {ret&&<div className={styles.overlay}><form className={styles.modal} onSubmit={retour}><h2>Retour {ret.reference}</h2><p><strong>{ret.numero_inventaire}</strong> — {ret.designation}</p><label>Emplacement de retour *<select required value={ret.emplacement_retour_id} onChange={e=>setRet({...ret,emplacement_retour_id:e.target.value})}><option value="">Sélectionner…</option>{refs.emplacements.map((x:any)=><option key={x.id} value={x.id}>{x.code} — {x.nom}</option>)}</select></label><label>État au retour *<select value={ret.etat_retour} onChange={e=>setRet({...ret,etat_retour:e.target.value})}><option value="DISPONIBLE">Disponible</option><option value="EN_MAINTENANCE">À mettre en maintenance</option><option value="HORS_SERVICE">Hors service</option></select></label><label>Commentaire retour<textarea value={ret.commentaire_retour} onChange={e=>setRet({...ret,commentaire_retour:e.target.value})}/></label><div className={styles.modalActions}><Button type="button" variant="secondary" onClick={()=>setRet(null)}>Annuler</Button><Button type="submit">Enregistrer le retour</Button></div></form></div>}
 {toast&&<Toast type={toast.type} message={toast.message} onClose={()=>setToast(null)}/>}</div>}
