"use client";

import { apiFetch } from "@/lib/api";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {CheckCircle2,ClipboardCheck,Plus,RefreshCcw,Search} from "lucide-react";
import {Button} from "@/components/ui/Button";
import {Toast} from "@/components/ui/Toast";
import {entetesAuthentifiees} from "@/lib/auth";
import styles from "./page.module.css";
const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000";
const eur=(v:any)=>Number(v??0).toLocaleString("fr-FR",{style:"currency",currency:"EUR"});
export default function Page(){const[data,setData]=useState<any[]>([]),[sel,setSel]=useState<any>(null),[modal,setModal]=useState(false),[q,setQ]=useState(""),[toast,setToast]=useState<any>(null),[f,setF]=useState({libelle:"",date_comptage:"",commentaire:""});
async function load(){const r=await apiFetch(`${API}/api/inventaires-avances`,{headers:entetesAuthentifiees()});if(r.ok){const d=await r.json();setData(d);if(sel)setSel(d.find((x:any)=>x.id===sel.id)??null)}else setToast({type:"error",message:"Chargement impossible."})}useEffect(()=>{load()},[]);
async function create(e:FormEvent){e.preventDefault();const r=await apiFetch(`${API}/api/inventaires-avances`,{method:"POST",headers:entetesAuthentifiees({"Content-Type":"application/json"}),body:JSON.stringify({libelle:f.libelle,date_comptage:f.date_comptage||null,commentaire:f.commentaire||null})});if(!r.ok)return setToast({type:"error",message:"Creation impossible."});setModal(false);load()}
async function count(l:any,v:string,j:string){const r=await apiFetch(`${API}/api/inventaires-avances/lignes/${l.id}`,{method:"PATCH",headers:entetesAuthentifiees({"Content-Type":"application/json"}),body:JSON.stringify({quantite_comptee:Number(v.replace(",",".")),justification:j||null})});const d=await r.json().catch(()=>null);if(!r.ok)return setToast({type:"error",message:d?.detail??"Comptage impossible."});await load()}
async function validate(){if(!sel||!confirm(`Valider ${sel.reference} et regulariser le stock ?`))return;const r=await apiFetch(`${API}/api/inventaires-avances/${sel.id}/valider`,{method:"POST",headers:entetesAuthentifiees()});const d=await r.json().catch(()=>null);if(!r.ok)return setToast({type:"error",message:d?.detail??"Validation impossible."});setToast({type:"success",message:"Inventaire valide et stock regularise."});load()}
const rows=useMemo(()=>data.filter(x=>!q||[x.reference,x.libelle,x.statut].some(v=>String(v).toLowerCase().includes(q.toLowerCase()))),[data,q]);
return <div><div className="breadcrumb">Inventaire / Campagnes & écarts</div><div className="page-heading page-heading-actions"><div><span className="eyebrow">Fiabilité du stock</span><h1>Inventaires avancés</h1><p>Comptage physique, analyse des écarts et régularisation contrôlée.</p></div><div className={styles.actions}><Button variant="secondary" onClick={load}><RefreshCcw size={17}/>Actualiser</Button><Button onClick={()=>setModal(true)}><Plus size={17}/>Nouvelle campagne</Button></div></div>
<section className={styles.grid}><div className={styles.panel}><label className="search-field"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Campagne…"/></label>{rows.map(x=><button key={x.id} className={`${styles.campaign} ${sel?.id===x.id?styles.active:""}`} onClick={()=>setSel(x)}><strong>{x.reference}</strong><span>{x.libelle}</span><small>{x.nb_comptees}/{x.nb_lignes} comptés · écart {eur(x.ecart_valeur_total)}</small></button>)}</div>
<div className={styles.panel}>{!sel?<div className={styles.empty}><ClipboardCheck size={38}/><p>Sélectionne une campagne.</p></div>:<><div className={styles.head}><div><h2>{sel.reference} — {sel.libelle}</h2><p>{sel.statut} · {sel.nb_comptees}/{sel.nb_lignes} lignes comptées</p></div>{sel.statut==="EN_COMPTAGE"&&<Button onClick={validate}><CheckCircle2 size={16}/>Valider l'inventaire</Button>}</div><table><thead><tr><th>Article</th><th>Emplacement</th><th>Théorique</th><th>Compté</th><th>Écart</th><th>Écart valeur</th><th>Justification</th></tr></thead><tbody>{sel.lignes.map((l:any)=><Ligne key={l.id} l={l} disabled={sel.statut!=="EN_COMPTAGE"} onSave={count}/>)}</tbody></table></>}</div></section>
{modal&&<div className={styles.overlay}><form className={styles.modal} onSubmit={create}><h2>Nouvelle campagne</h2><label>Libellé *<input required value={f.libelle} onChange={e=>setF({...f,libelle:e.target.value})} placeholder="Inventaire magasin principal"/></label><label>Date de comptage<input type="date" value={f.date_comptage} onChange={e=>setF({...f,date_comptage:e.target.value})}/></label><label>Commentaire<textarea value={f.commentaire} onChange={e=>setF({...f,commentaire:e.target.value})}/></label><div className={styles.modalActions}><Button type="button" variant="secondary" onClick={()=>setModal(false)}>Annuler</Button><Button type="submit">Créer</Button></div></form></div>}{toast&&<Toast type={toast.type} message={toast.message} onClose={()=>setToast(null)}/>}</div>}
function Ligne({l,disabled,onSave}:any){const[v,setV]=useState(l.quantite_comptee??""),[j,setJ]=useState(l.justification??"");const ec=l.quantite_comptee==null?null:Number(l.quantite_comptee)-Number(l.quantite_theorique);return <tr><td><strong>{l.reference_article}</strong><br/><span>{l.designation}</span></td><td>{l.emplacement}</td><td>{l.quantite_theorique}</td><td><input disabled={disabled} value={v} onChange={e=>setV(e.target.value)} onBlur={()=>v!==""&&onSave(l,v,j)}/></td><td className={ec&&ec!==0?styles.diff:""}>{ec??"—"}</td><td>{l.ecart_valeur==null?"—":eur(l.ecart_valeur)}</td><td><input disabled={disabled} value={j} onChange={e=>setJ(e.target.value)} onBlur={()=>v!==""&&onSave(l,v,j)} placeholder={ec&&ec!==0?"Obligatoire si écart":""}/></td></tr>}
