"use client";

import { apiFetch } from "@/lib/api";
import {FormEvent,useEffect,useState} from "react";
import {Plus,RefreshCcw,Search} from "lucide-react";
import {Button} from "@/components/ui/Button";import {Toast} from "@/components/ui/Toast";import {entetesAuthentifiees} from "@/lib/auth";import styles from "./page.module.css";
const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000";
export default function Page(){const[data,setData]=useState<any[]>([]),[recs,setRecs]=useState<any[]>([]),[q,setQ]=useState(""),[edit,setEdit]=useState<any>(null),[create,setCreate]=useState(false),[toast,setToast]=useState<any>(null),[f,setF]=useState<any>({reception_id:"",quantite_concernee:"",description:"",responsable:""});
async function load(){try{const h=entetesAuthentifiees();const[a,b]=await Promise.all([apiFetch(`${API}/api/non-conformites-fournisseurs`,{headers:h}),apiFetch(`${API}/api/receptions-qualite`,{headers:h})]);if(!a.ok||!b.ok)throw 0;setData(await a.json());setRecs(await b.json())}catch{setToast({type:"error",message:"Impossible de charger les non-conformités."})}}
useEffect(()=>{load()},[]);
async function saveCreate(e:FormEvent){e.preventDefault();const r=await apiFetch(`${API}/api/non-conformites-fournisseurs`,{method:"POST",headers:entetesAuthentifiees({"Content-Type":"application/json"}),body:JSON.stringify({...f,reception_id:Number(f.reception_id),quantite_concernee:Number(String(f.quantite_concernee).replace(",","."))})});const d=await r.json().catch(()=>null);if(!r.ok){setToast({type:"error",message:d?.detail??"Création impossible."});return}setCreate(false);setToast({type:"success",message:`${d.reference} créée.`});load()}
async function saveEdit(e:FormEvent){e.preventDefault();const r=await apiFetch(`${API}/api/non-conformites-fournisseurs/${edit.id}`,{method:"PATCH",headers:entetesAuthentifiees({"Content-Type":"application/json"}),body:JSON.stringify({decision:edit.decision||null,responsable:edit.responsable||"",statut:edit.statut,commentaire_traitement:edit.commentaire_traitement||""})});const d=await r.json().catch(()=>null);if(!r.ok){setToast({type:"error",message:d?.detail??"Modification impossible."});return}setEdit(null);load()}
const term=q.toLowerCase();const rows=data.filter(x=>!term||[x.reference,x.commande_reference,x.fournisseur,x.article_reference,x.article_designation].some(v=>String(v).toLowerCase().includes(term)));const eligible=recs.filter(x=>["SOUS_RESERVE","NON_CONFORME"].includes(x.statut_qualite)&&!x.ncf_id);
return <div><div className="breadcrumb">Fournisseurs / Achats / Non-conformités</div><div className="page-heading page-heading-actions"><div><span className="eyebrow">Qualité fournisseurs</span><h1>Non-conformités fournisseurs</h1><p>Suivi des écarts détectés à réception et des décisions de traitement. Les décisions sont exécutées dans Retours & litiges.</p></div><div className={styles.actions}><Button variant="secondary" onClick={load}><RefreshCcw size={17}/>Actualiser</Button><Button onClick={()=>{setF({reception_id:"",quantite_concernee:"",description:"",responsable:""});setCreate(true)}}><Plus size={17}/>Créer une NCF</Button></div></div><section className={styles.kpis}><article><span>Ouvertes</span><strong>{data.filter(x=>x.statut==="OUVERTE").length}</strong></article><article><span>En traitement</span><strong>{data.filter(x=>x.statut==="EN_TRAITEMENT").length}</strong></article><article><span>Clôturées</span><strong>{data.filter(x=>x.statut==="CLOTUREE").length}</strong></article><article><span>Réceptions à convertir</span><strong>{eligible.length}</strong></article></section><section className={styles.panel}><div className={styles.toolbar}><label className="search-field"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="NCF, commande, fournisseur ou article…"/></label></div><table className={styles.table}><thead><tr><th>NCF</th><th>Fournisseur</th><th>Commande</th><th>Article / lot</th><th>Qté</th><th>Décision</th><th>Responsable</th><th>Statut</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.reference}</strong></td><td>{x.fournisseur}</td><td>{x.commande_reference}</td><td><strong>{x.article_reference}</strong><br/><span>{x.article_designation} · {x.lot_reference??"sans lot"}</span></td><td>{x.quantite_concernee} {x.unite}</td><td>{x.decision?.replaceAll("_"," ")??"—"}</td><td>{x.responsable??"—"}</td><td><span className={styles.badge}>{x.statut.replaceAll("_"," ")}</span></td><td><button onClick={()=>setEdit({...x})}>Éditer</button></td></tr>)}{!rows.length&&<tr><td colSpan={9} className={styles.empty}>Aucune non-conformité.</td></tr>}</tbody></table></section>
{create&&<div className={styles.overlay}><form className={styles.modal} onSubmit={saveCreate}><h2>Nouvelle non-conformité</h2><label>Réception concernée *<select required value={f.reception_id} onChange={e=>{const r=eligible.find(x=>x.id===Number(e.target.value));setF({...f,reception_id:e.target.value,quantite_concernee:r?String(r.quantite):""})}}><option value="">Sélectionner…</option>{eligible.map(x=><option key={x.id} value={x.id}>{x.commande_reference} — {x.article_reference} — {x.fournisseur}</option>)}</select></label><label>Quantité concernée *<input required value={f.quantite_concernee} onChange={e=>setF({...f,quantite_concernee:e.target.value})}/></label><label>Description *<textarea required value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label><label>Responsable<input value={f.responsable} onChange={e=>setF({...f,responsable:e.target.value})}/></label><div className={styles.modalActions}><Button type="button" variant="secondary" onClick={()=>setCreate(false)}>Annuler</Button><Button type="submit">Créer la NCF</Button></div></form></div>}
{edit&&<div className={styles.overlay}><form className={styles.modal} onSubmit={saveEdit}><h2>{edit.reference}</h2><p>{edit.fournisseur} · {edit.article_reference} — {edit.article_designation}</p><label>Décision<select value={edit.decision??""} onChange={e=>setEdit({...edit,decision:e.target.value})}><option value="">À définir</option><option value="ACCEPTE_EN_ETAT">Accepté en l'état</option><option value="TRI">Tri</option><option value="RETOUR_FOURNISSEUR">Retour fournisseur</option><option value="REMPLACEMENT">Remplacement</option><option value="AVOIR">Avoir</option></select></label><label>Responsable<input value={edit.responsable??""} onChange={e=>setEdit({...edit,responsable:e.target.value})}/></label><label>Statut<select value={edit.statut} onChange={e=>setEdit({...edit,statut:e.target.value})}><option value="OUVERTE">Ouverte</option><option value="EN_TRAITEMENT">En traitement</option><option value="CLOTUREE">Clôturée</option></select></label><label>Traitement<textarea value={edit.commentaire_traitement??""} onChange={e=>setEdit({...edit,commentaire_traitement:e.target.value})}/></label><div className={styles.modalActions}><Button type="button" variant="secondary" onClick={()=>setEdit(null)}>Annuler</Button><Button type="submit">Enregistrer</Button></div></form></div>}{toast&&<Toast type={toast.type} message={toast.message} onClose={()=>setToast(null)}/>}</div>}
