"use client";

import { apiFetch } from "@/lib/api";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {AlertTriangle,CalendarClock,Plus,RefreshCcw,Search,Wrench} from "lucide-react";
import {Button} from "@/components/ui/Button";import {Toast} from "@/components/ui/Toast";import {entetesAuthentifiees} from "@/lib/auth";import { MaterielTabs } from "@/components/materiel/MaterielTabs";
import styles from "./page.module.css";
const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000";const df=(v:any)=>v?new Intl.DateTimeFormat("fr-FR").format(new Date(v)):"—";const eur=(v:any)=>v==null?"—":Number(v).toLocaleString("fr-FR",{style:"currency",currency:"EUR"});
const TYPE:any={PREVENTIVE:"Préventive",CORRECTIVE:"Corrective",CONTROLE_PERIODIQUE:"Contrôle périodique",ETALONNAGE:"Étalonnage",AUTRE:"Autre"};
export default function Page(){const[data,setData]=useState<any[]>([]),[dash,setDash]=useState<any>(null),[refs,setRefs]=useState<any>(null),[q,setQ]=useState(""),[modal,setModal]=useState(false),[edit,setEdit]=useState<any>(null),[toast,setToast]=useState<any>(null),[f,setF]=useState<any>({materiel_id:"",type_intervention:"PREVENTIVE",description:"",date_planifiee:"",prestataire:""});
async function load(){try{const h=entetesAuthentifiees();const[a,b,c]=await Promise.all([apiFetch(`${API}/api/maintenance-materiel`,{headers:h}),apiFetch(`${API}/api/maintenance-materiel/dashboard`,{headers:h}),apiFetch(`${API}/api/prets-materiel/referentiels`,{headers:h})]);if(!a.ok||!b.ok||!c.ok)throw 0;setData(await a.json());setDash(await b.json());setRefs(await c.json())}catch{setToast({type:"error",message:"Impossible de charger la maintenance matériel."})}}useEffect(()=>{load()},[]);
const rows=useMemo(()=>{const t=q.toLowerCase().trim();return data.filter(x=>!t||[x.reference,x.numero_inventaire,x.designation,x.type_intervention,x.prestataire].some(v=>String(v??"").toLowerCase().includes(t)))},[data,q]);
async function create(e:FormEvent){e.preventDefault();const r=await apiFetch(`${API}/api/maintenance-materiel`,{method:"POST",headers:entetesAuthentifiees({"Content-Type":"application/json"}),body:JSON.stringify({materiel_id:Number(f.materiel_id),type_intervention:f.type_intervention,description:f.description,date_planifiee:f.date_planifiee||null,prestataire:f.prestataire||null})});const d=await r.json().catch(()=>null);if(!r.ok){setToast({type:"error",message:d?.detail??"Création impossible."});return}setModal(false);load()}
async function save(e:FormEvent){e.preventDefault();const r=await apiFetch(`${API}/api/maintenance-materiel/${edit.id}`,{method:"PATCH",headers:entetesAuthentifiees({"Content-Type":"application/json"}),body:JSON.stringify({statut:edit.statut,date_planifiee:edit.date_planifiee||null,diagnostic:edit.diagnostic||null,action_realisee:edit.action_realisee||null,prestataire:edit.prestataire||null,cout_ht:edit.cout_ht===""?null:Number(String(edit.cout_ht).replace(",",".")),prochain_controle:edit.prochain_controle||null})});const d=await r.json().catch(()=>null);if(!r.ok){setToast({type:"error",message:d?.detail??"Modification impossible."});return}setEdit(null);load()}
return <div><div className="breadcrumb">Matériels / Maintenance & contrôles</div><MaterielTabs /><div className="page-heading page-heading-actions"><div><span className="eyebrow">Parc matériel</span><h1>Maintenance & contrôles</h1><p>Planification, interventions, contrôles périodiques et remise en service.</p></div><div className={styles.actions}><Button variant="secondary" onClick={load}><RefreshCcw size={17}/>Actualiser</Button><Button onClick={()=>{setF({materiel_id:"",type_intervention:"PREVENTIVE",description:"",date_planifiee:"",prestataire:""});setModal(true)}}><Plus size={17}/>Nouvelle intervention</Button></div></div>
{dash&&<><section className={styles.kpis}><article><Wrench/><span>Interventions ouvertes</span><strong>{dash.interventions_ouvertes}</strong></article><article><Wrench/><span>En maintenance</span><strong>{dash.materiels_en_maintenance}</strong></article><article className={styles.warn}><AlertTriangle/><span>Contrôles en retard</span><strong>{dash.controles_en_retard}</strong></article><article><CalendarClock/><span>Contrôles à 30 j</span><strong>{dash.controles_30_jours}</strong></article></section><section className={styles.controls}><h2>Échéances de contrôle</h2><div>{dash.controles.map((x:any)=><article key={x.materiel_id}><strong>{x.numero_inventaire}</strong><span>{x.designation}</span><b>{df(x.date_prochain_controle)}</b><small className={x.statut==="EN_RETARD"?styles.red:""}>{x.statut.replaceAll("_"," ")}</small></article>)}{!dash.controles.length&&<p>Aucune échéance dans les 30 jours.</p>}</div></section></>}
<section className={styles.panel}><div className={styles.toolbar}><label className="search-field"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Intervention, matériel, type ou prestataire…"/></label></div><table className={styles.table}><thead><tr><th>Intervention</th><th>Matériel</th><th>Type</th><th>Planifiée</th><th>Statut</th><th>Prestataire</th><th>Coût HT</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.reference}</strong></td><td><strong>{x.numero_inventaire}</strong><br/><span>{x.designation}</span></td><td>{TYPE[x.type_intervention]??x.type_intervention}</td><td>{df(x.date_planifiee)}</td><td><span className={styles.badge}>{x.statut.replaceAll("_"," ")}</span></td><td>{x.prestataire??"—"}</td><td>{eur(x.cout_ht)}</td><td><button onClick={()=>setEdit({...x,cout_ht:x.cout_ht??"",prochain_controle:x.prochain_controle??""})}>Éditer</button></td></tr>)}{!rows.length&&<tr><td colSpan={8} className={styles.empty}>Aucune intervention.</td></tr>}</tbody></table></section>
{modal&&<div className={styles.overlay}><form className={styles.modal} onSubmit={create}><h2>Nouvelle intervention</h2><label>Matériel *<select required value={f.materiel_id} onChange={e=>setF({...f,materiel_id:e.target.value})}><option value="">Sélectionner…</option>{refs?.materiels?.map((x:any)=><option key={x.id} value={x.id}>{x.numero_inventaire} — {x.designation} — {x.etat}</option>)}</select></label><label>Type *<select value={f.type_intervention} onChange={e=>setF({...f,type_intervention:e.target.value})}>{Object.entries(TYPE).map(([v,l])=><option key={v} value={v}>{String(l)}</option>)}</select></label><label>Date planifiée<input type="date" value={f.date_planifiee} onChange={e=>setF({...f,date_planifiee:e.target.value})}/></label><label>Prestataire<input value={f.prestataire} onChange={e=>setF({...f,prestataire:e.target.value})}/></label><label>Description *<textarea required value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label><div className={styles.modalActions}><Button type="button" variant="secondary" onClick={()=>setModal(false)}>Annuler</Button><Button type="submit">Créer</Button></div></form></div>}
{edit&&<div className={styles.overlay}><form className={styles.modal} onSubmit={save}><h2>{edit.reference}</h2><p><strong>{edit.numero_inventaire}</strong> — {edit.designation}</p><label>Statut<select value={edit.statut} onChange={e=>setEdit({...edit,statut:e.target.value})}><option value="A_PLANIFIER">À planifier</option><option value="PLANIFIEE">Planifiée</option><option value="EN_COURS">En cours</option><option value="TERMINEE">Terminée</option><option value="ANNULEE">Annulée</option></select></label><label>Date planifiée<input type="date" value={edit.date_planifiee??""} onChange={e=>setEdit({...edit,date_planifiee:e.target.value})}/></label><label>Diagnostic<textarea value={edit.diagnostic??""} onChange={e=>setEdit({...edit,diagnostic:e.target.value})}/></label><label>Action réalisée<textarea value={edit.action_realisee??""} onChange={e=>setEdit({...edit,action_realisee:e.target.value})}/></label><label>Prestataire<input value={edit.prestataire??""} onChange={e=>setEdit({...edit,prestataire:e.target.value})}/></label><label>Coût HT<input value={edit.cout_ht} onChange={e=>setEdit({...edit,cout_ht:e.target.value})}/></label><label>Prochain contrôle<input type="date" value={edit.prochain_controle??""} onChange={e=>setEdit({...edit,prochain_controle:e.target.value})}/></label><div className={styles.modalActions}><Button type="button" variant="secondary" onClick={()=>setEdit(null)}>Annuler</Button><Button type="submit">Enregistrer</Button></div></form></div>}
{toast&&<Toast type={toast.type} message={toast.message} onClose={()=>setToast(null)}/>}</div>}
